version: '3.4'
services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: celery-factory-demo
    container_name: some_api
    command: python entrypoint_api.py --port 8080 --debug
    env_file:
     - ./docker.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: celery-factory-demo
    container_name: some_worker
    depends_on:
      - redis
      - rabbitmq
    command: celery worker -A entrypoint_celery.celery --loglevel=info
    env_file:
     - ./docker.env
    volumes:
      - .:/app/
  redis:
    image: redis:alpine
    container_name: some_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  rabbitmq:
    image: rabbitmq:alpine
    container_name: some_rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5